#pragma once
#include <iostream>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <stb/stb_image.h>

#include "Window.h"
#include "Camera.h"
#include "TriangleShader.h"
#include "ShapeDefiner.h"
#include "ShapeGenerator.h"
#include "Texture.h"
#include "Skybox.h"
#include "Create3Dobject.h"
#include "Cubemap.h"
#include "Cubemap.h"
#include "Light.h"